language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4"
    - php: "nightly"
    - php: "hhvm"
  allow_failures:
    - php: "7.4"
    - php: "nightly"
    - php: "hhvm"

install:
    - composer self-update
    - composer update

script:
    - vendor/bin/phpunit
    - vendor/bin/psalm
